/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lorne_jni_JNIDemo */

#ifndef _Included_com_lorne_jni_JNIDemo
#define _Included_com_lorne_jni_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lorne_jni_JNIDemo
 * Method:    hi
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lorne_jni_JNIDemo_hi
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lorne_jni_JNIDemo
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lorne_jni_JNIDemo_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
